spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cclub?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /ems

mybatis:
  type-aliases-package: main.cclub.demo
  mapper-locations: classpath:mapper/*.xml
